# -*- coding: utf-8 -*-
"""personality_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16dr4B_x67kynYsJtiVg_LeKR93MtEAYC
"""

from google.colab import drive
drive.mount('/content/drive')

# custom_nlp and import libraries 
import gensim
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from gensim.models import Word2Vec
from sklearn.cluster import KMeans
import os
import re 
import spacy
from gensim.utils import simple_preprocess
from gensim import corpora
custom_nlp=spacy.load('en_core_web_sm')

#Tag remover funtion
def remove(txt,doc):
  try:
    doc=doc.replace(txt,'')
  except:
    txt="\\"+txt
    doc=doc.replace(txt,'')
  return doc

def remove_unwanted_extra(removeable_text_list,doc):
  try:
    for txt in removeable_text_list:
      doc=remove(txt,doc)
  except Exception as e:
    print(e)
    return 
  return doc
  
# lemmatization 
def lemmatize(doc):
  return list(set(token.lemma_ for  token in doc))
# remove Unwanted things from nlp object
def remove_unwanted(doc):
  words=list(set(token for token in doc if not token.is_stop and len(token.text)>2 and not token.is_space and not token.text.isdigit() and not token.is_punct and not token.is_bracket and not token.is_quote and not token.like_url and not token.like_num and not token.like_email and any([str(i) in ['a','e','i','o','u'] for i in token.text]) ))
  return lemmatize(words)
# file line iterator 
def file_line(path):
  for line in open(path,'r',encoding='unicode_escape').readlines():
    yield line.lower()

# df=pd.read_csv('/content/drive/My Drive/Company Workspace/C_dataset/mbti_1.csv') 
# pd.set_option('display.max_colwidth',-1)
# pd.option_context('display.max_columns',None)
# df['posts'][:2]

# cat_list=df['type'].to_list()
# unique_categories=df.drop_duplicates('type')['type'].to_list()
# samples_category={cat:cat_list.count(cat) for cat in unique_categories}
# print(samples_category)

# un_lst=['\t','\n',\\x]
# vocab={cat:[] for cat in unique_categories}
# for i in range(len(df)):
#   vocab[df['type'][i]].extend(list(set(remove_unwanted(custom_nlp( re.sub('[\d.,;:\'\"\\!<>@#$%^&?*\(\)\{\}\[\]\=\+\-/`~\|]',' ',remove_unwanted_extra(un_lst,df['posts'][i])) )) )))
#   print(i)

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation
from keras.layers.embeddings import Embedding
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelBinarizer
from keras.preprocessing.text import Tokenizer
from sklearn.model_selection import  train_test_split
from keras.preprocessing.sequence import pad_sequences

df2=pd.read_csv('/content/drive/My Drive/mbti_preprocessed.csv')
pd.set_option('display.max_colwidth',-1)
pd.option_context('display.max_columns',None)
print(df2.head())

#cat_list=df2['type'].to_list()
#unique_categories=df2.drop_duplicates('type')['type'].to_list()
#samples_category={cat:cat_list.count(cat) for cat in unique_categories}
#print(samples_category)

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
onehotencoder = OneHotEncoder(categorical_features = [1])
X= onehotencoder.fit_transform(X).toarray()



tokenizer=Tokenizer(nb_words=None, lower=True, split=" ")
tokenizer.fit_on_texts(df2['posts'].values)
#print(tokenizer.word_index)  # To see the dicstionary
X = tokenizer.texts_to_sequences(df2['posts'].values)
X = pad_sequences(X,maxlen=200,padding='post',truncating='pre')
# Le=LabelBinarizer()
# Y=Le.fit_transform(df2['type'])
Y=df2['type'].map({cat:i for i,cat in enumerate(unique_categories)})
X_train, X_valid, Y_train, Y_valid = train_test_split(X,Y, test_size = 0.20, random_state = 36)

Y[14]

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 70, kernel_initializer = 'uniform', activation = 'relu', input_dim = 200))
    classifier.add(Dropout(0.2))
    classifier.add(Dense(units = 70, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(0.1))
    classifier.add(Dense(units = 40, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(0.2))
    classifier.add(Dense(units = 30, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'softmax'))
    classifier.compile(optimizer = optimizer, loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)
parameters = {'batch_size': [25, 32,37],
              'epochs': [100,400,600],
              'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train, Y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

def main_r(optimizer):
  embed_dim = 128
  batch_size = 32
  model = Sequential()
  model.add(Embedding(200000, 128, input_length=200))
  model.add(LSTM(200, dropout=0.2, recurrent_dropout=0.2,return_sequences=True))
  model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
  model.add(Dense(16, activation='softmax'))  
  model.compile(loss = 'sparse_categorical_crossentropy', optimizer=optimizer,metrics = ['accuracy'])
 # model.fit(X_train, Y_train, batch_size =batch_size, nb_epoch = 30,  verbose = 1)
  return model
classifier = KerasClassifier(build_fn = main_r)
parameters = {'batch_size': [25, 32,37],
              'epochs': [100,400,600],
              'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train, Y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_
print(grid_search,best_parameters,best_accuracy)

# f=open('/content/drive/My Drive/mbti_vocab.txt','w+')
# f.write(str(vocab))
# f.close()

# (I: introversion ,S:Sensing ,T : Thinking ,J: judging ,F:feeling,N:intution ,P:percelving ,E:extraversion ,)
# ISTJ   
# Quiet, serious, earn success by thoroughness and dependability. Practical, matter-of-fact, realistic, and responsible. Decide logically what should be done and work toward it steadily, regardless of distractions. Take pleasure in making everything orderly and organized - their work, their home, their life. Value traditions and loyalty.

# ISFJ
# Quiet, friendly, responsible, and conscientious. Committed and steady in meeting their obligations. Thorough, painstaking, and accurate. Loyal, considerate, notice and remember specifics about people who are important to them, concerned with how others feel. Strive to create an orderly and harmonious environment at work and at home.

# INFJ
# Seek meaning and connection in ideas, relationships, and material possessions. Want to understand what motivates people and are insightful about others. Conscientious and committed to their firm values. Develop a clear vision about how best to serve the common good. Organized and decisive in implementing their vision.

# INTJ
# Have original minds and great drive for implementing their ideas and achieving their goals. Quickly see patterns in external events and develop long-range explanatory perspectives. When committed, organize a job and carry it through. Skeptical and independent, have high standards of competence and performance - for themselves and others.

# ISTP
# Tolerant and flexible, quiet observers until a problem appears, then act quickly to find workable solutions. Analyze what makes things work and readily get through large amounts of data to isolate the core of practical problems. Interested in cause and effect, organize facts using logical principles, value efficiency.

# ISFP
# Quiet, friendly, sensitive, and kind. Enjoy the present moment, what's going on around them. Like to have their own space and to work within their own time frame. Loyal and committed to their values and to people who are important to them. Dislike disagreements and conflicts, do not force their opinions or values on others.

# INFP
# Idealistic, loyal to their values and to people who are important to them. Want an external life that is congruent with their values. Curious, quick to see possibilities, can be catalysts for implementing ideas. Seek to understand people and to help them fulfill their potential. Adaptable, flexible, and accepting unless a value is threatened.

# INTP
# Seek to develop logical explanations for everything that interests them. Theoretical and abstract, interested more in ideas than in social interaction. Quiet, contained, flexible, and adaptable. Have unusual ability to focus in depth to solve problems in their area of interest. Skeptical, sometimes critical, always analytical.

# ESTP
# Flexible and tolerant, they take a pragmatic approach focused on immediate results. Theories and conceptual explanations bore them - they want to act energetically to solve the problem. Focus on the here-and-now, spontaneous, enjoy each moment that they can be active with others. Enjoy material comforts and style. Learn best through doing.

# ESFP
# Outgoing, friendly, and accepting. Exuberant lovers of life, people, and material comforts. Enjoy working with others to make things happen. Bring common sense and a realistic approach to their work, and make work fun. Flexible and spontaneous, adapt readily to new people and environments. Learn best by trying a new skill with other people.

# ENFP
# Warmly enthusiastic and imaginative. See life as full of possibilities. Make connections between events and information very quickly, and confidently proceed based on the patterns they see. Want a lot of affirmation from others, and readily give appreciation and support. Spontaneous and flexible, often rely on their ability to improvise and their verbal fluency.

# ENTP
# Quick, ingenious, stimulating, alert, and outspoken. Resourceful in solving new and challenging problems. Adept at generating conceptual possibilities and then analyzing them strategically. Good at reading other people. Bored by routine, will seldom do the same thing the same way, apt to turn to one new interest after another.

# ESTJ
# Practical, realistic, matter-of-fact. Decisive, quickly move to implement decisions. Organize projects and people to get things done, focus on getting results in the most efficient way possible. Take care of routine details. Have a clear set of logical standards, systematically follow them and want others to also. Forceful in implementing their plans.

# ESFJ
# Warmhearted, conscientious, and cooperative. Want harmony in their environment, work with determination to establish it. Like to work with others to complete tasks accurately and on time. Loyal, follow through even in small matters. Notice what others need in their day-by-day lives and try to provide it. Want to be appreciated for who they are and for what they contribute.

# ENFJ
# Warm, empathetic, responsive, and responsible. Highly attuned to the emotions, needs, and motivations of others. Find potential in everyone, want to help others fulfill their potential. May act as catalysts for individual and group growth. Loyal, responsive to praise and criticism. Sociable, facilitate others in a group, and provide inspiring leadership.

# ENTJ
# Frank, decisive, assume leadership readily. Quickly see illogical and inefficient procedures and policies, develop and implement comprehensive systems to solve organizational problems. Enjoy long-term planning and goal setting. Usually well informed, well read, enjoy expanding their knowledge and passing it on to others. Forceful in presenting their ideas.


# Excerpted from Introduction to Type® by Isabel Briggs Myers published by The Myers-Briggs Company. Used with permission.
